# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |vm|
    vm.memory = 2048
    vm.cpus = 2
  end
  config.vm.define :ICTV2Centos6 do |t|
  end
  config.vm.box = "centos/6"
  config.vm.provision "shell", path: "provision_as_root.sh"
  config.vm.provision "shell", path: "provision_as_normal_user.sh", privileged: false
  config.vm.network :forwarded_port, guest: 80, host: 8081
end
